apiVersion: v1
kind: Pod
metadata:
  name: kihyun-nginx
  namespace: kihyun
  labels: # labels는 service의 라우팅 대상이 되는 이름이며, service의 selector.app을 통해 매핑
    app: kihyun-nginx
spec: 
  containers:
  - name: kihyun-nginx
    image: nginx
    ports:
    - containerPort: 80
